name: zenify
description: A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 0.0.1+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^2.0.12 # Required for SVG icon support
  english_words: ^4.0.0
  http: ^1.6.0
  provider: ^6.0.0
  window_size: ^0.1.0
  shared_preferences: ^2.2.2
  image_picker: ^1.1.2
  camera: ^0.11.1+4
  path_provider: ^2.0.2
  flutter_plugin_android_lifecycle: ^2.0.28
  fl_chart: ^0.65.0
  intl: ^0.20.2
  cached_network_image: ^3.3.0
  carousel_slider: ^5.1.1
  connectivity_plus: ^6.1.0
  gradient_borders: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/figma/
    - assets/images/
    - assets/images/eating_styles/
    - assets/transition/
  fonts:
    - family: iconfont
      fonts:
        - asset: assets/fonts/iconfont.ttf
    - family: PressStart2P
      fonts:
        - asset: assets/fonts/PressStart2P-Regular.ttf
    - family: PressStart2P
      fonts:
        - asset: assets/fonts/PressStart2P-Regular.ttf
